version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: delivery_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    command: --local-infile=1  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: .
    container_name: etl_container
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - C:\Users\juane\Documents\delivery_project2\proyecto_delivery\proyecto_delivery:/data
    command: python ETL.py

volumes:
  mysql_data: